#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Set the formatter to 'html'
  formatter: stylish
# File Options
files:
  include: 'scss/**/*.s+(a|c)ss'
  ignore:
    - 'scss/reset.scss'
    - 'scss/normalise.scss'
    - 'scss/base.scss'
# Rule Configuration
rules:
  indentation:
    - 2
    -
      size: 2
